name: CICD

on:
  push:
    branches: [main,master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t nodejs-aws-elk-fcm .
      - name: Publish image to Docker Hub
        run: docker push nodejs-aws-elk-fcm:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from Docker Hub
        run: docker pull nodejs-aws-elk-fcm:latest
      - name: Delete old container
        run: docker rm -f nodejs-aws-elk-fcm-container
      - name: Run a new container
        run: docker run -d -p 3003:3003 --name nodejs-aws-elk-fcm-container nodejs-aws-elk-fcm:latest